In [1]:
import keras
import time
import matplotlib
import matplotlib.pyplot as plt

from keras.layers import Dense, Activation
from keras.models import Sequential
from keras.datasets import mnist
from keras.layers import LeakyReLU

# Load datasets and view the shape of the training and test dataset splits
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print("Training data shape: ", x_train.shape) 
print("Training label shape: ", y_train.shape)

print("Test data shape", x_test.shape)
print("Test label shape: ", y_test.shape)

# Reshape the test and train labels datasets to avoid rank 1 arrays
y_train = y_train.reshape(len(y_train), 1)
print("Reshaped training label: ", y_train.shape)
y_test = y_test.reshape(len(y_test), 1)
print("Reshaped test label: ", y_test.shape)

# Flatten the images
flatten_image_size = x_train.shape[1] * x_train.shape[2] #Training and Test images should have the same dimensions
x_train = x_train.reshape(x_train.shape[0], flatten_image_size)
x_test = x_test.reshape(x_test.shape[0], flatten_image_size)

print("First 5 training labels: \n", y_train[:5])

# Convert to "one-hot" vectors using the to_categorical function
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print("First 5 training lables as one-hot encoded vectors:\n", y_train[:5])

Using TensorFlow backend.


Training data shape:  (60000, 28, 28)
Training label shape:  (60000,)
Test data shape (10000, 28, 28)
Test label shape:  (10000,)
Reshaped training label:  (60000, 1)
Reshaped test label:  (10000, 1)
First 5 training labels: 
 [[5]
 [0]
 [4]
 [1]
 [9]]
First 5 training lables as one-hot encoded vectors:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [2]:
num_classes = 10 # Number of different outputsts

model = Sequential()

model.add(Dense(32), input_shape=(flatten_image_size,))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(64))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(num_classes, activation='softmax'))

TypeError: add() got an unexpected keyword argument 'input_shape'

In [ ]:
model.compile(optimizer="sgd", loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=512, epochs=10, verbose=1, validation_split=.1)
loss, accuracy  = model.evaluate(x_test, y_test, verbose=False)
model.summary()
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['Training', 'Test'], loc='best')
plt.show()

print(f'Test loss: {loss:.3}')
print(f'Test accuracy: {accuracy:.3}')